#!/bin/sh
# Rogatka OpenCode profile for a laptop (macOS / Linux): builds the guard plugin, writes a dedicated config and a
# `rogatka-opencode` launcher. Your normal OpenCode config (~/.config/opencode) is never written to.
#
#   sh deploy/opencode-remote/setup.sh [--demo-repo DIR]
#
# Overrides (environment):
#   ROGATKA_GATEWAY_URL   gateway base URL, no /v1        default https://rogatka-api.b.solvro.pl
#   ROGATKA_OIDC_ISSUER   Keycloak realm URL (issuer)      default https://rogatka-auth.b.solvro.pl/realms/acl
#   ROGATKA_HOME          profile dir (config + plugin)    default ${XDG_CONFIG_HOME:-~/.config}/rogatka-opencode
#   ROGATKA_BIN_DIR       where the launcher goes          default ~/.local/bin
#   ROGATKA_SKIP_TESTS=1  skip the plugin's unit tests (not recommended)
set -eu

GATEWAY_URL="${ROGATKA_GATEWAY_URL:-https://rogatka-api.b.solvro.pl}"
OIDC_ISSUER="${ROGATKA_OIDC_ISSUER:-https://rogatka-auth.b.solvro.pl/realms/acl}"
PROFILE="${ROGATKA_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/rogatka-opencode}"
BIN_DIR="${ROGATKA_BIN_DIR:-$HOME/.local/bin}"
MCP_SERVERS="governed-tools,files,mail,web"
DEMO_REPO=""

while [ $# -gt 0 ]; do
  case "$1" in
    --demo-repo) [ $# -ge 2 ] || { echo "--demo-repo needs a directory" >&2; exit 2; }; DEMO_REPO="$2"; shift 2 ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

die() { echo "setup: $1" >&2; exit 1; }

# Strip trailing slashes; the plugin wants the base URL without /v1 and refuses plain http to public hosts.
GATEWAY_URL=$(printf '%s' "$GATEWAY_URL" | sed 's:/*$::')
OIDC_ISSUER=$(printf '%s' "$OIDC_ISSUER" | sed 's:/*$::')
case "$GATEWAY_URL" in */v1) die "ROGATKA_GATEWAY_URL must not end in /v1 ($GATEWAY_URL)";; esac
# These values are substituted into JSON with sed: refuse characters that would need escaping there.
case "$GATEWAY_URL$OIDC_ISSUER$PROFILE" in
  *'"'*|*'\'*|*'|'*|*'&'*) die "URLs and ROGATKA_HOME must not contain quotes, backslashes, '|' or '&'";;
esac

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
PLUGIN_SRC="$REPO_ROOT/plugins/opencode-guard"
[ -f "$PLUGIN_SRC/package.json" ] || die "plugin sources not found at $PLUGIN_SRC"

command -v node >/dev/null 2>&1 || die "Node.js >= 20 is required (https://nodejs.org)"
if ! command -v pnpm >/dev/null 2>&1; then
  command -v corepack >/dev/null 2>&1 || die "pnpm is required (npm i -g pnpm, or corepack enable)"
  corepack enable pnpm || die "pnpm is required (npm i -g pnpm)"
fi
command -v opencode >/dev/null 2>&1 || echo "note: 'opencode' is not on PATH yet; install it before running rogatka-opencode (see README)" >&2

echo "==> building the guard plugin ($PLUGIN_SRC)"
pnpm -C "$PLUGIN_SRC" install --frozen-lockfile
pnpm -C "$PLUGIN_SRC" run typecheck
if [ "${ROGATKA_SKIP_TESTS:-}" != "1" ]; then pnpm -C "$PLUGIN_SRC" test; fi
pnpm -C "$PLUGIN_SRC" run build

echo "==> installing the plugin into $PROFILE/opencode-guard"
mkdir -p "$PROFILE"
rm -rf "$PROFILE/opencode-guard"
mkdir -p "$PROFILE/opencode-guard"
cp "$PLUGIN_SRC/package.json" "$PROFILE/opencode-guard/package.json"
cp -R "$PLUGIN_SRC/dist" "$PROFILE/opencode-guard/dist"

echo "==> writing $PROFILE/opencode.json"
# Absolute plugin paths are accepted by OpenCode (converted to file:// URLs when the config is loaded).
sed -e "s|__GATEWAY_URL__|$GATEWAY_URL|g" -e "s|__GUARD_PLUGIN__|$PROFILE/opencode-guard|g" \
  "$SCRIPT_DIR/opencode.template.json" > "$PROFILE/opencode.json"

LAUNCHER="$BIN_DIR/rogatka-opencode"
echo "==> writing launcher $LAUNCHER"
mkdir -p "$BIN_DIR"
q() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Generated by deploy/opencode-remote/setup.sh: OpenCode with the Rogatka profile (company gateway + guard plugin).
set -eu
# Drop caller-set OPENCODE_* switches (OPENCODE_PURE would skip the guard plugin; OPENCODE_CONFIG_CONTENT /
# OPENCODE_CONFIG_DIR / OPENCODE_PERMISSION would add config sources), then set the profile.
for var in \$(env | sed -n 's/^\(OPENCODE_[A-Za-z0-9_]*\)=.*/\1/p'); do unset "\$var"; done
unset ACL_OIDC_BASE_URL ACL_ALLOW_INSECURE_HTTP
export OPENCODE_CONFIG=$(q "$PROFILE/opencode.json")
export OPENCODE_DISABLE_PROJECT_CONFIG=1   # a cloned repo's opencode.json / .opencode/ must not change the setup
export OPENCODE_DISABLE_AUTOUPDATE=1
export OPENCODE_DISABLE_MODELS_FETCH=1     # model list comes from the profile; the gateway is the model authority
export ACL_GATEWAY_URL=$(q "$GATEWAY_URL")
export ACL_OIDC_ISSUER=$(q "$OIDC_ISSUER")
export ACL_OIDC_CLIENT_ID=opencode
export ACL_MCP_SERVERS=$(q "$MCP_SERVERS")
export ACL_CLIENT_VERSION="\${ACL_CLIENT_VERSION:-opencode-remote}"
exec opencode "\$@"
EOF
chmod 0755 "$LAUNCHER"

if [ -n "$DEMO_REPO" ]; then
  [ ! -e "$DEMO_REPO" ] || die "$DEMO_REPO already exists; pick a new directory"
  echo "==> copying the poisoned demo repo to $DEMO_REPO"
  mkdir -p "$DEMO_REPO"
  cp -R "$REPO_ROOT/deploy/opencode/demo-repo/." "$DEMO_REPO/"
  (cd "$DEMO_REPO" && git init -q && git -c core.autocrlf=false add -A \
    && git -c user.name=demo -c user.email=demo@corp.example commit -q -m "Initial import") \
    || echo "note: git init of the demo repo failed; it still works without git" >&2
fi

echo
echo "Done. Profile: $PROFILE"
case ":$PATH:" in *":$BIN_DIR:"*) ;; *) echo "Add $BIN_DIR to PATH (or run $LAUNCHER directly).";; esac
echo "Next:  rogatka-opencode auth login     (choose 'company', open the link, sign in as a demo user)"
echo "Then:  cd <repo> && rogatka-opencode"
