<#
.SYNOPSIS
  Rogatka OpenCode profile for a Windows laptop: builds the guard plugin, writes a dedicated config and a
  rogatka-opencode.cmd launcher. Your normal OpenCode config (~\.config\opencode) is never written to.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File deploy\opencode-remote\setup.ps1
  powershell -ExecutionPolicy Bypass -File deploy\opencode-remote\setup.ps1 -DemoRepo $HOME\rogatka-demo -AddToPath
#>
[CmdletBinding()]
param(
  # Gateway base URL, without /v1.
  [string]$GatewayUrl = $(if ($env:ROGATKA_GATEWAY_URL) { $env:ROGATKA_GATEWAY_URL } else { "https://rogatka-api.b.solvro.pl" }),
  # Keycloak realm URL (token issuer).
  [string]$OidcIssuer = $(if ($env:ROGATKA_OIDC_ISSUER) { $env:ROGATKA_OIDC_ISSUER } else { "https://rogatka-auth.b.solvro.pl/realms/acl" }),
  # Profile directory: generated config, installed plugin and the launcher.
  [string]$ProfileDir = $(if ($env:ROGATKA_HOME) { $env:ROGATKA_HOME } else { Join-Path $env:LOCALAPPDATA "rogatka-opencode" }),
  # Optional: copy the poisoned demo repository here (must not exist yet).
  [string]$DemoRepo = "",
  # Add the profile directory (with rogatka-opencode.cmd) to the user PATH.
  [switch]$AddToPath,
  # Skip the plugin's unit tests (not recommended).
  [switch]$SkipTests
)
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Fail([string]$message) { Write-Host "setup: $message" -ForegroundColor Red; exit 1 }
function Run([string]$exe, [string[]]$arguments) {
  & $exe @arguments
  if ($LASTEXITCODE -ne 0) { Fail "'$exe $($arguments -join ' ')' failed with exit code $LASTEXITCODE" }
}
function Write-Utf8NoBom([string]$path, [string]$text) {
  [System.IO.File]::WriteAllText($path, $text, (New-Object System.Text.UTF8Encoding $false))
}

$GatewayUrl = $GatewayUrl.TrimEnd("/")
$OidcIssuer = $OidcIssuer.TrimEnd("/")
if ($GatewayUrl -match "/v1$") { Fail "GatewayUrl must not end in /v1 ($GatewayUrl)" }
foreach ($u in @($GatewayUrl, $OidcIssuer)) {
  $parsed = $null
  if (-not [System.Uri]::TryCreate($u, [System.UriKind]::Absolute, [ref]$parsed) -or ($parsed.Scheme -ne "https" -and $parsed.Scheme -ne "http")) {
    Fail "not an http(s) URL: $u"
  }
  if ($u -match '["\\%^&|<>\s]') { Fail "URL contains characters that are not allowed here: $u" }
}

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$PluginSrc = Join-Path $RepoRoot "plugins\opencode-guard"
if (-not (Test-Path (Join-Path $PluginSrc "package.json"))) { Fail "plugin sources not found at $PluginSrc" }

if (-not (Get-Command node -ErrorAction SilentlyContinue)) { Fail "Node.js >= 20 is required (https://nodejs.org)" }
if (-not (Get-Command pnpm -ErrorAction SilentlyContinue)) {
  if (Get-Command corepack -ErrorAction SilentlyContinue) {
    & corepack enable pnpm
    if ($LASTEXITCODE -ne 0) { Fail "pnpm is required (npm i -g pnpm)" }
  } else { Fail "pnpm is required (npm i -g pnpm, or corepack enable)" }
}
if (-not (Get-Command opencode -ErrorAction SilentlyContinue)) {
  Write-Host "note: 'opencode' is not on PATH yet; install it before running rogatka-opencode (see README)" -ForegroundColor Yellow
}

Write-Host "==> building the guard plugin ($PluginSrc)"
Run "pnpm" @("-C", $PluginSrc, "install", "--frozen-lockfile")
Run "pnpm" @("-C", $PluginSrc, "run", "typecheck")
if (-not $SkipTests) { Run "pnpm" @("-C", $PluginSrc, "test") }
Run "pnpm" @("-C", $PluginSrc, "run", "build")

$PluginDir = Join-Path $ProfileDir "opencode-guard"
Write-Host "==> installing the plugin into $PluginDir"
New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
if (Test-Path $PluginDir) { Remove-Item -Recurse -Force $PluginDir }
New-Item -ItemType Directory -Force -Path $PluginDir | Out-Null
Copy-Item (Join-Path $PluginSrc "package.json") (Join-Path $PluginDir "package.json")
Copy-Item -Recurse (Join-Path $PluginSrc "dist") (Join-Path $PluginDir "dist")

# OpenCode resolves file:// plugin specs with Node's fileURLToPath, so file:///C:/... works on Windows.
$PluginUri = ([System.Uri](Resolve-Path $PluginDir).Path).AbsoluteUri
$ConfigPath = Join-Path $ProfileDir "opencode.json"
Write-Host "==> writing $ConfigPath"
$template = [System.IO.File]::ReadAllText((Join-Path $PSScriptRoot "opencode.template.json"))
$config = $template.Replace("__GATEWAY_URL__", $GatewayUrl).Replace("__GUARD_PLUGIN__", $PluginUri)
$null = $config | ConvertFrom-Json  # fail here rather than in OpenCode if the result is not valid JSON
Write-Utf8NoBom $ConfigPath $config

# The launcher refers to its own directory (%~dp0), so no user-specific (possibly non-ASCII) path is baked into it.
$Launcher = Join-Path $ProfileDir "rogatka-opencode.cmd"
Write-Host "==> writing launcher $Launcher"
$cmd = @"
@echo off
rem Generated by deploy/opencode-remote/setup.ps1: OpenCode with the Rogatka profile (company gateway + guard plugin).
setlocal
rem Drop caller-set OPENCODE_* switches (OPENCODE_PURE would skip the guard plugin; OPENCODE_CONFIG_CONTENT,
rem OPENCODE_CONFIG_DIR, OPENCODE_PERMISSION would add config sources), then set the profile.
for /f "tokens=1 delims==" %%V in ('set OPENCODE_ 2^>nul') do set "%%V="
set "ACL_OIDC_BASE_URL="
set "ACL_ALLOW_INSECURE_HTTP="
set "OPENCODE_CONFIG=%~dp0opencode.json"
rem A cloned repo's opencode.json / .opencode/ must not change the setup.
set "OPENCODE_DISABLE_PROJECT_CONFIG=1"
set "OPENCODE_DISABLE_AUTOUPDATE=1"
rem The model list comes from the profile; the gateway is the model authority.
set "OPENCODE_DISABLE_MODELS_FETCH=1"
set "ACL_GATEWAY_URL=$GatewayUrl"
set "ACL_OIDC_ISSUER=$OidcIssuer"
set "ACL_OIDC_CLIENT_ID=opencode"
set "ACL_MCP_SERVERS=governed-tools,files,mail,web"
if not defined ACL_CLIENT_VERSION set "ACL_CLIENT_VERSION=opencode-remote"
opencode %*
"@
[System.IO.File]::WriteAllText($Launcher, ($cmd -replace "`r?`n", "`r`n"), (New-Object System.Text.ASCIIEncoding))

if ($DemoRepo) {
  if (Test-Path $DemoRepo) { Fail "$DemoRepo already exists; pick a new directory" }
  Write-Host "==> copying the poisoned demo repo to $DemoRepo"
  New-Item -ItemType Directory -Force -Path $DemoRepo | Out-Null
  Copy-Item -Recurse -Path (Join-Path $RepoRoot "deploy\opencode\demo-repo\*") -Destination $DemoRepo
  if (Get-Command git -ErrorAction SilentlyContinue) {
    & git -C $DemoRepo init -q
    & git -C $DemoRepo -c core.autocrlf=false add -A
    & git -C $DemoRepo -c user.name=demo -c user.email=demo@corp.example commit -q -m "Initial import"
    if ($LASTEXITCODE -ne 0) { Write-Host "note: git commit in the demo repo failed; it still works without git" -ForegroundColor Yellow }
  }
}

if ($AddToPath) {
  $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
  $parts = @()
  if ($userPath) { $parts = $userPath.Split(";") | Where-Object { $_ } }
  if ($parts -notcontains $ProfileDir) {
    [Environment]::SetEnvironmentVariable("Path", (($parts + $ProfileDir) -join ";"), "User")
    Write-Host "==> added $ProfileDir to the user PATH (open a new terminal)"
  }
}

Write-Host ""
Write-Host "Done. Profile: $ProfileDir"
if (-not $AddToPath) { Write-Host "Run the launcher by full path, or re-run with -AddToPath:  $Launcher" }
Write-Host "Next:  rogatka-opencode auth login     (choose 'company', open the link, sign in as a demo user)"
Write-Host "Then:  cd <repo>; rogatka-opencode"
